apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitcoind-mainnet
  namespace: bitcoin-shared
spec:
  interval: 5m
  chart:
    spec:
      chart: bitcoind
      version: "0.3.4"
      sourceRef:
        kind: HelmRepository
        name: bitcoin-helm-charts
        namespace: bitcoin-shared
  values:
    extraEnv:
      MALLOC_ARENA_MAX: 1

    arguments:
      - -chain=testnet4
      - -printtoconsole
      - -bind=$(MY_POD_IP)
      - -listen
      - -server
      - -rpcbind=$(MY_POD_IP)
      - -rpcallowip=10.0.0.0/8
      - -persistmempool
      - -txindex=1
      - -dbcache=2000
      - -par=1
      - -rpcthreads=8
      - -maxconnections=40
      - -maxorphantx=10
      - -maxuploadtarget=1000
      - -blockfilterindex=1
      - -rpcworkqueue=50
      - -zmqpubrawblock=tcp://0.0.0.0:18444
      - -zmqpubrawtx=tcp://0.0.0.0:18445
      - -zmqpubhashblock=tcp://0.0.0.0:18446
    
    # Find this secret in ./secrets. The secret contains RPC credentials
    configExternalSecretName: bitcoin-shared-testnet4-config

    strategyType: Recreate

    service:
      ports:
        tcp:
          - 18332
          - 18444
          - 18445
          - 18446
      type: ClusterIP

    persistence:
      enabled: true
      storageClass: proxmox-data
      size: 400Gi

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true

    resources:
      limits:
        cpu: 1.5
        memory: 8000Mi
      requests:
        cpu: 0.3
        memory: 1000Mi

    extraManifests:
      - |
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        metadata:
          labels:
            {{- include "bitcoind.labels" . | nindent 4 }}
          name: {{ template "bitcoind.fullname" . }}
        spec:
          entryPoints:
          # Ensure that you have an entrypoint configured for traefik, like this:
          #  additionalArguments:
          #  - "--entrypoints.bitcoind-18332.address=:18332"
          - bitcoind-18332
          routes:
          - match: HostSNI(`*`)
            services:
            - name: {{ include "bitcoind.fullname" . }}
              port: 18332
