---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitcoin-helm-charts
  namespace: bitcoin-shared
spec:
  interval: 1h
  url: https://bitcoin-helm-charts.boerst.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitcoind-mainnet
  namespace: bitcoin-shared
spec:
  interval: 5m
  chart:
    spec:
      chart: bitcoind
      version: "0.3.5"
      sourceRef:
        kind: HelmRepository
        name: bitcoin-helm-charts
        namespace: bitcoin-shared
  values:
    extraEnv:
      MALLOC_ARENA_MAX: 1

    arguments:
      - -printtoconsole
      - -bind=$(MY_POD_IP)
      - -listen
      - -server
      - -rpcbind=$(MY_POD_IP)
      - -rpcallowip=10.0.0.0/8
      - -persistmempool
      - -txindex=1
      - -dbcache=2000
      - -par=1
      - -rpcthreads=8
      - -maxconnections=40
      - -maxorphantx=10
      - -maxuploadtarget=1000
      - -blockfilterindex=1
      - -rpcworkqueue=50
      - -zmqpubrawblock=tcp://0.0.0.0:58444
      - -zmqpubrawtx=tcp://0.0.0.0:58445
      - -zmqpubhashblock=tcp://0.0.0.0:58446
    
    # Find this secret in ./secrets. The secret contains RPC credentials
    configExternalSecretName: bitcoin-shared-mainnet-config

    strategyType: Recreate

    service:
      ports:
        tcp:
          - 8433
          - 58444
          - 58445
      type: ClusterIP

    persistence:
      enabled: true
      storageClass: proxmox-data-expandable
      size: 1Ti

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true

    resources:
      limits:
        cpu: 1.5
        memory: 8000Mi
      requests:
        cpu: 0.3
        memory: 1000Mi

    extraManifests:
      - |
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        metadata:
          labels:
            {{- include "bitcoind.labels" . | nindent 4 }}
          name: {{ template "bitcoind.fullname" . }}
        spec:
          entryPoints:
          # Ensure that you have an entrypoint configured for traefik, like this:
          #  additionalArguments:
          #  - "--entrypoints.bitcoind-8332.address=:8332"
          - bitcoind-8332
          routes:
          - match: HostSNI(`*`)
            services:
            - name: {{ include "bitcoind.fullname" . }}
              port: 8332
        ---
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        metadata:
          labels:
            {{- include "bitcoind.labels" . | nindent 4 }}
          name: {{ template "bitcoind.fullname" . }}-58444
        spec:
          entryPoints:
          # Ensure that you have an entrypoint configured for traefik, like this:
          #  additionalArguments:
          #  - "--entrypoints.bitcoind-58444.address=:58444"
          - bitcoind-58444
          routes:
          - match: HostSNI(`*`)
            services:
            - name: {{ include "bitcoind.fullname" . }}
              port: 58444
        ---
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        metadata:
          labels:
            {{- include "bitcoind.labels" . | nindent 4 }}
          name: {{ template "bitcoind.fullname" . }}-58445
        spec:
          entryPoints:
          # Ensure that you have an entrypoint configured for traefik, like this:
          #  additionalArguments:
          #  - "--entrypoints.bitcoind-58445.address=:58445"
          - bitcoind-58445
          routes:
          - match: HostSNI(`*`)
            services:
            - name: {{ include "bitcoind.fullname" . }}
              port: 58445
