---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fulcrum-signet
  namespace: bitcoin-shared
spec:
  interval: 5m
  chart:
    spec:
      chart: fulcrum
      version: "0.1.8"
      sourceRef:
        kind: HelmRepository
        name: bitcoin-helm-charts
        namespace: bitcoin-shared
  values:
    config: |
      datadir = /data
      bitcoind = bitcoind-signet:18332
      rpcuser = electrum-server
      # rpcpassword is being set using RPCPASSWORD environment variable, stored in rpcPasswordEnvVarSecretName secret

      # *RECOMMENDED* - TCP bind - 'tcp' - DEFAULT: 0.0.0.0:50001, Specifies the IPv4
      # or IPv6 interface:port to bind to.
      tcp = 0.0.0.0:30001

      # *RECOMMENDED* - SSL bind - 'ssl' - DEFAULT: Noting, Specifies the IPv4 or IPv6
      # interface:port to bind to. The presence of this variable requires key= and
      # cert= both be specified.
      ssl = 0.0.0.0:30002

      # *RECOMMENDED* - WS bind - 'ws' - DEFAULT: Nothing, Specifies the IPv4 or IPv6
      # interface:port to bind to for Web Socket support (ws://).
      ws = 0.0.0.0:30003

      # SSL cert. - 'cert' - DEFAULT: None (required for SSL) (PEM, self-signed ok)
      cert = /ssl/tls.crt

      # SSL private key - 'key' - DEFAULT: None (required for SSL) (PEM format)
      key = /ssl/tls.key

      # Public hostname - 'hostname' - It is highly recommended you set this correctly
      # if you are interested in having your server peer with other servers --
      # otherwise other servers may not peer with you if your hostname is missing or
      # does not resolve to your public IP address.
      hostname = fulcrum-signet.lab.bitcoinpark.com

      # Peer discovery - 'peering' - DEFAULT: true - If false, do not contact peers to
      # discover other servers.
      peering = false

      # Peering: announce self - 'announce' - DEFAULT: true if hostname and peering
      # are set, false otherwise. If true and the aforementioned conditions are met,
      # then your server will announce itself to peers
      announce = false

    rpcPasswordEnvVarSecretName: bitcoin-signet-electrum-server-rpcpassword

    service:
      ports:
        tcp:
          - 30001
          - 30002

    persistence:
      enabled: true
      storageClass: proxmox-data
      size: 100Gi

    ssl:
      enabled: true
      certificate:
        dnsNames:
          - "fulcrum-signet.lab.bitcoinpark.com"

    resources:
      limits:
        cpu: 800m
        memory: 2000Mi
      requests:
        cpu: 300m
        memory: 1100Mi

    extraManifests:
      - |
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        metadata:
          labels:
            {{- include "fulcrum.labels" . | nindent 4 }}
          name: {{ template "fulcrum.fullname" . }}-30001
        spec:
          entryPoints:
          # Ensure that you have an entrypoint configured for traefik, like this:
          #  additionalArguments:
          #  - "--entrypoints.fulcrum-30001.address=:30001"
          - fulcrum-30001
          routes:
          - match: HostSNI(`*`)
            services:
            - name: {{ include "fulcrum.fullname" . }}
              port: 30001
        ---
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        metadata:
          labels:
            {{- include "fulcrum.labels" . | nindent 4 }}
          name: {{ template "fulcrum.fullname" . }}-30002
        spec:
          entryPoints:
          # Ensure that you have an entrypoint configured for traefik, like this:
          #  additionalArguments:
          #  - "--entrypoints.fulcrum-30002.address=:30002"
          - fulcrum-30002
          routes:
          - match: HostSNI(`*`)
            services:
            - name: {{ include "fulcrum.fullname" . }}
              port: 30002
