---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mempool-space-mainnet
  namespace: bitcoin-shared
spec:
  interval: 5m
  chart:
    spec:
      chart: mempool
      version: "0.1.14"
      sourceRef:
        kind: HelmRepository
        name: bitcoin-helm-charts
        namespace: bitcoin-shared
  values:
    frontend:
      env:
        BACKEND_MAINNET_HTTP_HOST: "mempool-space-mainnet-backend-mainnet"
      ingress:
        enabled: true
        ingressClassName: traefik-internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - mempool.lab.bitcoinpark.com
        tls:
        - hosts:
          - mempool.lab.bitcoinpark.com
          secretName: mempool-mainnet-tls

    backends:
      - name: mainnet
        image:
          repository: mempool/backend
          tag: v3.0.1
          pullPolicy: IfNotPresent

        strategyType: Recreate

        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""

        env:
          NODE_OPTIONS: "--max-old-space-size=3072" 
          BISQ_ENABLED: "false"
          LIQUID_ENABLED: "false"
          LIGHTNING: "false"
        
        envExternalSecretName: mempool-space-mainnet-env-vars

        coreRpcHost: bitcoind-mainnet
        coreRpcPort: 8332
        coreRpcUsername: mempool-space-mainnet
        coreRpcPassword: "" # Can also be set using envExternalSecretName above
        statisticsEnabled: true

        mempoolBackend:
          type: electrum
          electrum:
            host: fulcrum-mainnet
            port: 50001
            tls: false

        arguments:
          # Send trace/debug info to console instead of debug.log file
          # - -printtoconsole

        podSecurityContext: {}
          # fsGroup: 2000

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault

        service:
          enabled: true

          annotations: {}
          labels: {}
          ## Deprecated, instead simply do not provide a clusterIP value
          omitClusterIP: false
          # clusterIP: ""

          ## List of IP addresses at which the controller services are available
          ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
          ##
          externalIPs: []

          loadBalancerIP: ""
          loadBalancerSourceRanges: []

          ## Set external traffic policy to: "Local" to preserve source IP on
          ## providers supporting it
          ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
          externalTrafficPolicy: ""

          # Must be either "None" or "ClientIP" if set. Kubernetes will default to "None".
          # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
          sessionAffinity: ""

          healthCheckNodePort: 0

          tcpPort: 8999

        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1.6
            memory: 2Gi

        nodeSelector: {}

        tolerations: []

        affinity: {}

    mariadb:
      primary:
        persistence:
          enabled: true
          storageClass: proxmox-data
          size: 8Gi
