---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: ldap-shared
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ldap-shared
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.2.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ldap-shared
  values:
    auth:
      existingSecret: ldap-shared-postgresql-auth
    storageClass: proxmox-data
