---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nonce-guess-helm-charts
  namespace: playground
spec:
  interval: 1h
  url: https://github.com/notmandatory/nonce_guess
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nonce-guess
  namespace: playground
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/nonce-guess
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: nonce-guess-helm-charts
        namespace: playground
  values:

    strategyType: Recreate

    service:
      ports:
        tcp:
          - 8080
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: traefik-internal
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - nonce.lab.bitcoinpark.com
      tls:
        - hosts:
            - nonce.lab.bitcoinpark.com
          secretName: nonce-mainnet-tls

    persistence:
      enabled: true
      storageClass: proxmox-data
      size: 5Gi

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true

    resources:
      limits:
        cpu: 1.5
        memory: 8000Mi
      requests:
        cpu: 0.3
        memory: 1000Mi

