---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.16.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    cluster:
      name: bplab
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    operator:
      replicas: 1
    routingMode: tunnel
    tunnelProtocol: vxlan
