---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: bplab-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: bplab-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.14.8"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: bplab-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    prometheus:
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: bplab-system
spec:
  addresses:
    - 10.21.0.150-10.21.0.190
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: bplab-system
spec:
  ipAddressPools:
    - main-pool
