apiVersion: v1
data:
    bitcoin.conf: ENC[AES256_GCM,data:tfD5aDYCoiJn8SGCEQwzY0uV4TUNTS55qdMGwg1ljQn+TlsrZNvmtKYjHb/xsl19hrAwm2FulPtlAT0HDiyeMVMq7yEPiCTFeNBM9zReilT2TEobDh4FuxXuQkUEZ008rRtxPQUDNSQ/7Q7642eCuEss6mUzZ/NHXrjrILhh9SUnJNpBZkNxlCojUCNOTMEKH6b4S/Y5BaXf4HBkA/JIP57HQEZrIZZHz3NGN6SIrNDUMb12f417RBtWyj7iga47HxKTSdzvTwfBhtuWrvhKb2GOFmRG2DtaO0xEGh9pIhjwLrvYr973aQquU8rCoZzBBsHgfshL8wmFfhm6HM0Ne8q6iKiA1P8u8nou40GU61pJEAyhDaqJNyzAtAngtz7kJ8TQoRqw78e/y+aqcPY8Z++JmmYHpQELADnYQrKFt/Je48Hnak6ouw==,iv:8WjpdhAwO3c4xQNnHvmYO7De9mLZh84W1IJ2K5n1ItM=,tag:3Cv0x592tRnoGL5Lrr5wSQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bitcoin-shared-mainnet-config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-05T21:29:32Z"
    mac: ENC[AES256_GCM,data:DcTnUTj+uiRiAwIKvkm6+F+aejy7tSZYlXARJ6G4PdL81Aof2cZ0C28TjTKtm1C8NvZ7CR/pMqCsVgUDiIQt0fKlBtoaR3atOP15eF8liNObu7nQfDnoFc/eqwwNZVh5m8g/wAmQxO0ximJYHFt7MOu54qwEZHEVvy7XV/pGB6Y=,iv:mjwhBGVcg1iiJyTzkKMqxbPI2OG3l3DNWbTb46g9/RY=,tag:BS0VaDUwF7yvvnBuOi+C+w==,type:str]
    pgp:
        - created_at: "2024-12-05T21:29:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5kb4uUr2TBNAQ/+JpIIiJIM3MhMnqfDW0defyhVhiEaUiUozU0vNXGwfF7K
            9fYSVO/gWFiGUyYu2cK2Ri4NS3i9nTRo1h04tJ/V7Atipa3AcCtUAGDEf6JYxh/c
            BswrrOtTj6pVvrYz7GfQFRqZJ/YvY9CZBltMVDKVvXL+JQBEg7BTbteQjo+vlH0M
            3oizqDCod8M63onwjDMpkH1WsvBrJ1dka6eYsRlTbW+yKwOscOzA7L/ZiphYRNoW
            /gig9/qQYEV3CgN4pHKIJ/8bpaPZ2/GJ6v49R7zQUc/Jq8wRukl1L5VBM+5uH3A5
            ML5KDCI9gTCKQpO1056Rw+PZ/ekHQ+J2Jtuvt8kh2DVF7a2TbveJyPlBL0xVJAf0
            RVXvLCWGNYgSDniJm4lBSDtAVoBKl5lCz7zbV0wQTTbarDBFYvEf7gFtKWxlx+HU
            AaP/agH6U+/B97+iBsWFTpdHZuW2XTrgvGGFCnM2REZaWfDRC650/XWcjdvZk+O0
            xSUMOIRjneyNYydS6qoDEdyF0gxlrehth1gmeBdh+teNxkYNDEfdNrmKyFmXK/Qf
            ogYlH2ujC4CPuzx4BPGQCx4U4//s4Qos1jOpvPtT5aOnUpe/+owJszRyr7iVo97d
            mIvD7PDjMkNF6FyVR78m2nqVkFGFbACwt6afjCxiUht+0eMY+H2SmxWgKVfCySbS
            XAEqRu+nafkGWiNDCuec5OlhWOgRJZWHalYzx/PJmkatLqlh/IjP7ePY/6SVSZ4D
            IJexAWXHJC8OIFBubr2x//KhWXrWNqcJKoCfVzFxRskrB1MhZ8EIz8QaEZ2J
            =OpIj
            -----END PGP MESSAGE-----
          fp: E0CF4C69516FD99B5F661E11C0084202BBFEA27B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
