apiVersion: v1
data:
    bitcoin.conf: ENC[AES256_GCM,data:dNuqaOzyIjfqatb93QI8sdlilZqLdPdgbB3XSW9sfAFDN7sbxmlvtNInMvAxPiAgWdQItv17dqUAjwGfZ4TORWa5cNC7VE5RojWPjoxKJSxAtZLiLT8dI5aanYD05q38HDxyDq7Km92/KqNObqHOPlREovhirL5Z+lw+z7W3/OZQY0ilHSu5vxnm75eYewRgg0UeSOF5LLmIGYwdbVw0eS9XqcEr2n9WwRfksxWawY7ztq7VAIqx2wzvt73TrRh0Uma90Kt87e8Uf7tTQol9aZSYKdAROVaDbxkXH8RCM/PRDgKzYk46TdWN51YDGdL74XpAxsXiUg65ipgRFd/0gQVlY9Srdjo+lp1herVNIPXgFg/S8Vqknl0aYvnUJP6wCg7w1NxuVeRnsM1+JU769SFJWD0VWk0mrOZvsv0KqU9AukXPbNKnha+F/ZIp1UZWgRww+l8/an/PaRzyvPK14j+yTrkfp/VdkVnTJpJ1gJVRSJShG2ncqo/SffV/v/tXCe8pOfxwiqJnu7p1N4l1es6TFrfV7VO0WAm19CJFXWXurjBsOz1ReEM4/b4XPw4poYjqgPF/0XGIjhpB8tbFVcfr0c7z1bSRSrQ4VPlIonRleN7YagH2ox71JTYsviZ3Mvpp99McfoY2sDHIZUI+IgObkXpzAaOuGaCXIsIzAgkXNrJezfgyvauKBIfvkSyBTeauZbMl0AFnH9BS/E0HdLIvA33rLb7/9MpqUkGbB8WUxBK84MdDBC11D365fiGEmwKOctKTQgcgTchtbtpMWJl29g3z0+fG1HXtHoiTf/2uYk+09whBzbn4LmDeXLCplKzcf8TyL+/aIuVA5beCX6zWONIqsEBdz6QoehcpAwk=,iv:Xb0VkEAOgw+ySiPfC+FfBhYgKH5wh32CCfoew6V/n5M=,tag:4SKtb6M1zmXpW+pv4hJjsQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bitcoin-shared-testnet4-config
    namespace: bitcoin-shared
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-17T20:26:26Z"
    mac: ENC[AES256_GCM,data:9Aj8mZRRSJyKESjvaWExaHEVM2JnFtUkRBLQTsriMwRNsin8VmYDJbQ2BZj6c0NdyCoxPZ+RrUjV3s7YOEnB1rePqhyoekDj2pIEMyuMk2J293nAw+ma72HR2KMleZolUDBHGmGFDLUDxnp1rgONMEy1Zldu0kSUu76gyQFSw7s=,iv:NVuBnXuPKzbuEZOBD8ESHYpeTl7A3WtDxsJWaVP6j9A=,tag:Bw4NiXOyd/0fx6PivzYkHg==,type:str]
    pgp:
        - created_at: "2025-02-17T20:26:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5kb4uUr2TBNARAA7kkufyBIqj8U33c5CDKImIB/dD7akUi3hlRWP26wTWuP
            /YrKJnPAOOZtQv6BHJxnHeX0/TBwrop8hyg5gC9i6Xv0eHZO0LZsHQ7vfEAaIeyf
            f7XNglLcCqRv/kfp4RI/rxunZDwIT2RO2RkxSZWtS0bJOIvQWdU8m++M+/ebWQNd
            mvXA7SZ3CiKi4HHNPmkr5kjiBpOlH7jA9S3t4lrmijSZJsUxRBCW5f8SuWx2mPHv
            ya6JVVq8+3osqYlrANQfp6PDnG9Tnk6QHNn95eME4ndDe9JWOeArBDVfqjAId0Y+
            LUifQVihtoEIKg8c6r65cOYq4Er/VgH7hXa/ft6AMFYSApnwgeNHXuwaGmuhbJsq
            I6xA/mqXAYs0jl7zsGkM62CuX7II+s9cuNwWm3c8b3t1HiU20Gn0kdu46ioCQL+U
            l6NFoUa6Wyow/2lEvgfxIq0aOa1yWK/1WLkegZOUY1itnW3/Dy/ZQEy4LDzZySuq
            WFDsYWDkJf4/yNAXsPZyIyzO81G+5HVmq0y/d6C7MH/1B5AxDgVKvcmYDR3PFa3/
            LpCDv4fsFNJ4vYQMi10dzhxhg+Y61FtAWVjRWvKqts5tzDO8PfAIO5pHUMoDWzUX
            RXxgeoKwuHASdfti1Qr5sW5R4MfxIfkBeFl3iWEQKlemVHfM39Iovrl50zv7gDTS
            XAGtO9ol7LYPGXJHIxXSKi4H8wWim8umkfhvf0q8pX25H5Hj8DLs1NG19e5ebt7c
            oeodZDHPUtEY2LTvkpdKmkBnxMmBMoxCTa1eXLyZgw9AnfuwbcqW9WdY/XLf
            =o/Nk
            -----END PGP MESSAGE-----
          fp: E0CF4C69516FD99B5F661E11C0084202BBFEA27B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
