apiVersion: v1
data:
    bitcoin.conf: ENC[AES256_GCM,data:K1wkRWk1pyy09XczZUHA88do25CJMvjJFazskN3S/lSF/eDUOOhYZAXzwsuklI1nf27fx3IESMm0WUnXMscMvOp0AsAhJqjrJXB6TiBInqGLHSWcVjTlJZ/ghJyp4eALGiEDCUN4iLaZkfUh+/s2jSzhQ1OSfQfYclICRglT5N40wh/lpKH1Ajb/+iWweTBsiG9cblPB+iMzHFIorWtG5YIjBf1sS4PVcV9rB6FAvAn6VYO0IGv5MbpzWpoh5spPx/M3gjB+A0a6NAf0qhSDvhoS3H3ke4KLZGNv+QsP76ZxVuOSRje9kQkT+/WsQT0eVbS3el++9mKrJG3nJfGqMG+DtsuXQ8QugInOSUL/8VgpA69xGxCs8MbtrbZY4QuZVN8UqqbmJVY8J5p4fPiNUx+nOmao++Tu2unViWOQrtouV4H/LPw1/YNM+PPFkTXXQ21+ttUmpGZP/A6Bgzhx5G4FiZiJC5oIs9RDfXmDUsi2fCPUpCKUTZnBU0UTjs4VfA4EXA/fyE7278ax8cNh7Yee0q8MzEj+qUG4cYYC6uMmL9ZWRJmfhgeLpQf0+F+xC9Q0QVvw6G76AsIDdFUwoGBjT1tVlaNGuBp+Y4FIxwNQj9rguKvwVReEyTAEmpZ9+w24zTzB5ixVnN0hwp3g3z+izcGW2I3mUg8GkzM27JJ0ljiQy8N0NeKg/HQBSHMUPBRVjIX9+6FTwIltOxq6tBg+QZD9ard7Iistq2OChN1xyIRCoOjy1hhe2EAZNYNEH0dPhcYGJD5ERUMfPVRWipHlREtMPctXj6pm5hjbwKr91v+p72WC4sH0hik2Djn5w5vCS/WXrPQQgls21CApbIRcrdTmK4uotXCEKA==,iv:8ZfT9ThUSI/uuWMP0akQT3gfzCaPC7BY8pD2ASngQxQ=,tag:7WvlPH1LzxwkRNhMg5j4pg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bitcoin-shared-signet-config
    namespace: bitcoin-shared
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-17T19:05:49Z"
    mac: ENC[AES256_GCM,data:NZ+eQtzeNIfSuBTw++4kXvoBviVW0mH1Y91KiCpjegcoP/0l+RIv3VC0dxeK9h1o1jJ1GuPZnwNnhAX3GhpbRFC2JJjBG1BuHBT1KywXQG11MSwNr4Ki3PbuFb25kkZHXY2FJdWzTnKi8+y9J2oDDWo2/R7qtjTDw1J80Pj5WC4=,iv:wok52ahYKkf/rewNpjcRS1Um8bQFQAVUCSiFcpfnsJ4=,tag:G6OaxYLBXHLjlBfyoPkqvA==,type:str]
    pgp:
        - created_at: "2025-02-17T19:05:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5kb4uUr2TBNAQ/+MMBJbqIcNosSxbJWaVUsd1TElKe8EpFlLly5q6te0E0G
            05XRNYjciNC3OcR//9lj0Mh5LcKAr3tcZx94H2UUx8uPC5xZglYpwZ1m2DN2Dq0N
            88LDzExqL7PEKb+a+mHt4po4G5Npd8HxVMhESylC7pQ8E1Guru+M8eQpe3Kc7rz5
            vk4dY2HpIwss+O7HUNbmlMZxXL7NWFW5auEh7dStSDEdmUALHMYb6GFz3H5U9CGI
            VjSaJe00idWRUWaJ8cXrpfivGQEACIRtSulsE0d8U/InX7JrI3gR9d+ulFOmwGti
            deQYPuksvZaW5C99B/HtZJgKBWME6etdJKW5BsYw2b+7hrTWCsqXkPl/h+V0YsTc
            5hrh/AP8MmeDLB9qUvaNuiYSIXOZ2XywihJhRZxna3cg8PlE00DkgFq7clzU24WM
            uc2k22mO1xE+nP7kdSSZJmcnfX0ug429QQvvoWLJdquul36Tendi333Q3t+NNotO
            pkcMJCpyoPHzUwxPS7ziVbY9S/go5G+rxerXaHAXJXMC6pGbsFAnT1vvP0g6+OsP
            b4lCxfz6k4dvKBkw3n6sefjrO6qmEVB+4m7c5pdBL8SZAZI5MnPOmtx4kmrWv8fJ
            fNme9JsJM2zmyNrH+QZEg1EPtmQHJk3WLx4G9oreKa1Dh9Znvh/lPPRnjQOj6xzS
            XAGojn9G996ly7zFuSQ+77ZopVnk2HRSAO5Dit28QCQRZztCfrjwntvHQ5za23uF
            wCtFKb3xf5VEb7zUs5KUN43JLCbgTLl8R7DIDfo+yjnkr9ZRJ0Dd3YFW5X3V
            =OG++
            -----END PGP MESSAGE-----
          fp: E0CF4C69516FD99B5F661E11C0084202BBFEA27B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
