apiVersion: v1
data:
    postgres-password: ENC[AES256_GCM,data:/9sEfjmBljNUn1XWLKJ0gvQ2G4Y1f6v3m2MxczROsWw/azrA,iv:OQ64SHH5AsRQSmLGxj16/SjB2NuuGVwHuthkBeoQCxw=,tag:Wkp9rHF69G3k6AQwzJJR1Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ldap-shared-postgresql-auth
    namespace: ldap-shared
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-08T19:07:39Z"
    mac: ENC[AES256_GCM,data:c1Vjf6e8Qa3Fj8p3PcGRbiX2iE7vzvd3JMhqhoak9Ir3hlagnfGaxXWaDhWvO4Mhkggxn90I5tOlwceMG9RpvXBHh1WhUb4sAaPdiFabgDsDoNEGxxY0nq5z9on+zo1i2iKhIWLpTC4fP0RpRBx5E1GXgaZLuWyg8A2rXxQRtQM=,iv:R4sSaL8mCeswd/e0tZk0o8DQZ0Iot76CVD2Us++m0Fs=,tag:wtFLhguyH04v5B6x1XeXwA==,type:str]
    pgp:
        - created_at: "2024-12-08T19:07:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5kb4uUr2TBNARAAtI8+8p59T/8dF/PR8weRsegwvqdkc3RKy+Ml01YrEsrr
            esoUbCMM4/anlGRM1oX1Atg7LTP5pWoc7sVTC1Jm5CKDxr4CP1uzcrbyWCszU18H
            4dXjLfjKkfrEenZkxiZlrCYsXj0PRpjKKjUusP2YoUxvboNyO1D8udFXjUu5OdyY
            oJDijan2tcpux9DOgd8+0uVs/saL5ACe2X1GeRuxwLm4w+Rz+y2KZUEX8Y+F2anc
            lhIhDK+jjcsmQUEsMUwJUoEvBQ2UE0KH02ZKR1xLBgMiQ4ZblNP70OkOpCDIUTNX
            OBHWZmYjp41a5EXQVZsNAmyfXxXUNPr5P1OBdZuG6dYYJZvPfzrNyUfi8sLy3Oqn
            zRLqPPWYcslcaIMAlfEEmt8GfSVKVbmfrn5yXrxkHjQsCJ0JH7H1MxiagQxxkv90
            f1bFNHp3ag9T6NQ6S6M9oM+UdpdaBCLBmEzjVw0PDXFSwRxWo9sHREGgtApGExK/
            FunACXmnQjahRBCdGPCVqXdp+u2kCNB++TYtMoXCnlU1YhlJtyFy0YjU/gpvoPlK
            S+LicQHkWjgvaRXHNZMUpVQf+NLgPxepAvYOvATsZ/ixhk0PQUYYeDk1fE4KdvVn
            TRqGafVgXa/h2LSNZThXfxg6D3RhJKyyYf72QuNCwx3Wsx65nUMBtBFtAAKpch3S
            UQENFiBtsgkRfczqOHrrs6bV9gTq17wzpwaQk5kMpsPDYUjMSBrl9657DK4MD3/f
            k86gADMkKGEHD1Zz8MehHxeQ1AiAbCC9u3doW8D4D3onBg==
            =9Z4h
            -----END PGP MESSAGE-----
          fp: E0CF4C69516FD99B5F661E11C0084202BBFEA27B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
