apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:av2XSHVWMH2sY+sMQ3/1x5VNHntYpHoDSRaqB+xL1INIQFBS02gA2bR6SARdDuFWZYcS2fhakE03NwA1x4dnuRB4BBSfevbcxYD/yzMfDI1hOSC3lZCWFqUwvco/PVJejQ4jvOGTuPHMiLyZxWvMxxyGZXq6VPAwBuwiucnfWFwAR3US+vLrQxe0FpHH7FM+uCKZdOJ2yIh3B/BmA/1MCpbQL9U5QWIRkAaLHv6N6vm+QCxx8RPUZrvlaYU5lzQEf2HhFGUUZaHYBQCdUS5vJEFju9E33+IidEQ/cvdg19IOr+UO8Fu9y5mx3bO9nZiKu/KLVuj+1BecQE6WcP+LNvMv6zmCZr6x,iv:ecA6O72ww4AZVjhfSuK0fxNMY4nI3Kq5T0gk4/YGyPs=,tag:n1gDJBB3645kNEV20Swwbg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: proxmox-csi-config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T19:55:55Z"
    mac: ENC[AES256_GCM,data:swLQB1muVkby78M8diA3SVfNGA7IRzl+EmO0jN+h268g8PuKa5sHKMICUKpOR31JjACY9K/ceAeKWztFXFzOsBJfqWW1DiddghBB73XBwvpejlmOMoBuarpJSjopEmHrCQWuEVnTpLxxrxjqbiykbrpT6VWWBGhQTx5ecNXkrpY=,iv:nIfR7kHgSeXXQ09qm1zN3PePVkaG2ndnFqDHIcc+5cs=,tag:uTiO5hKU36muzjCZjf+2aQ==,type:str]
    pgp:
        - created_at: "2024-11-19T19:55:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5kb4uUr2TBNARAA2zhmgihHUu6rrrVzEbI/afynf9Krb7/IxHhDymc8R8a1
            cRRO5Bvru2fXGTM43dECrXFor1VusUKuZrPtk8J++6858dTl1dQ8oW4VeEABFR0p
            dBaJ52Ex0NtCgp1BWlOJM/82246QoK9/TUo4o0GVSftWY77dhjNSL3yqV9b4D9vL
            KJM4Yy0s/sCg80wR8CehABfaTb0GSgeHald69SSr58tD9pqgXU0jixXgiqk56sIh
            xKTdZOYtdJamZ8pQmFv4kpfo1WRRkMJOoFWvzI/7KfZOkRgWLyX+qvlxi9nFI6eg
            HvsqQXssEzG+iOeYmXiTJSG2Fqz0pa5gB2nM4wtAGEh0VfDOqgvvvVgObSvSKDf7
            978p6qMJHL9XkDigza/+sor63eP0LFAvlgaoCyuCh/GpvdNntIKcbJeg4RfCIPlM
            lBxChOV4wjzXg2t0OB60bEpt/28h73XZXZZsO8us3vywDY20DduCLxnJgbyuGwgd
            U1Cv6/CsMhl65y6ZqxBLO1V3waSeSn7o3S2975s+tpxIfooC/hMNqh5EorZR2b2l
            9ycB+ubYpKPvQRlKcX7PDxW4takTM20mg663x+9UCVvD/I69fQmPhdqRhaIieST1
            MiUmQ8k9frMK8ZuxvFRbbJdQb/AaHJO/ucStUKTn+YbCzRSxpCV39RjTeuU20WPS
            XgGUPeDP9hwtCG/d4ExRMfZandMLpb9nbJ8u0/Ku36ea+shgkQtt2CUp+3Ftt8xX
            9fesQ9cPNWtKaTimYD9zVCgnwcUIah7mmqi28dh8zG/R439IXTjJ4/akTE08HZA=
            =Hcc8
            -----END PGP MESSAGE-----
          fp: E0CF4C69516FD99B5F661E11C0084202BBFEA27B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
