---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-proxmox
  namespace: bplab-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/sergelogvinov/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
  namespace: bplab-system
spec:
  interval: 5m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: "0.2.13"
      sourceRef:
        kind: HelmRepository
        name: csi-proxmox
        namespace: bplab-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    existingConfigSecret: proxmox-csi-config
    # See https://pve.proxmox.com/wiki/Storage
    storageClass:
      - name: proxmox-data
        storage: DATA
        reclaimPolicy: Retain
        fstype: ext4
        cache: writethrough